##### WARNING the docker compose does not work any more and I cannot figure out why it is not.
##### The backend keep installing dependencies for frontend even though it has package.json for backend
##### Please use npm run dev for both frontend and backend

version: '3.8'

services:
  frontend:
    build: .
    container_name: wirecracker-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend  # Exclude backend folder from frontend volumes
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      dockerfile: backend/Dockerfile
    container_name: wirecracker-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
